#!/bin/sh
set -e
# Automatically added by dh_installsystemd/13.3.1
if [ -d /run/systemd/system ] && [ "$1" = remove ]; then
	deb-systemd-invoke stop 'haveged.service' >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installinit/13.3.1
if [ -x "/etc/init.d/haveged" ] && [ "$1" = remove ]; then
	invoke-rc.d --skip-systemd-native haveged stop || exit 1
fi
# End automatically added section
